config/routes.rb
CookieGame::Application.routes.draw do
  root 'games#home'
  post '/add-sessions' => 'games#add_sessions', as: 'add_session'
  get '/new-game' => 'games#new_game', as: 'new_game'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  def home
    @number = session[:number].to_i + session[:old_number].to_i
    if @number > 20
      @score_class = 'its_over'
      elsif @number == 20
      @score_class = 'good_game'
      elsif @number >= 14
      @score_class = 'orange'
      elsif @number > 9
      @score_class = 'yellow'
    end

  end

  def add_sessions

    session[:number] = params[:number]
    session[:old_number] = params[:current_number]
    redirect_to root_url
  end

  def new_game
    reset_session

    redirect_to root_url
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/home.html.erb
<style type="text/css">

</style>

<div class="container">
<h1 class="<%= @score_class %>">Number: <%= @number %></h1>


  <%= link_to '1', add_session_url(number: 1, current_number: @number), method: 'post', class: 'btn btn-primary btn-lg' %>
  <%= link_to '2', add_session_url(number: 2, current_number: @number), method: 'post', class: 'btn btn-primary btn-lg' %>
  <%= link_to '3', add_session_url(number: 3, current_number: @number), method: 'post', class: 'btn btn-primary btn-lg'%>

  <br>
  <br>


    <% if @number == 20 %>

      <h1 class="game_message">You won. Other dude lost.</h1>
      <%= link_to 'New Game', new_game_url, class: 'new_game' %>

    <% elsif @number > 20%>

      <h1 class="game_message">You either won, or you just don't get it.</h1>
      <%= link_to 'New Game', new_game_url, class: 'new_game btn btn-danger' %>

    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CookieGame</title>
  <link rel="stylesheet" type="text/css" href="http://netdna.bootstrapcdn.com/bootstrap/3.0.2/css/bootstrap.min.css">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>